extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  max-len: ['error', 85]
  react/prop-types: off
  react/display-name: off
  no-unneeded-ternary: error
  no-nested-ternary: error
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-ts-comment': off

settings:
  react:
    version: 18.2.0
