singleQuote:          true
semi:                 false
trailingComma:        none
jsxBracketSameLine:   true
jsxSingleQuote:       true
tabWidth:             4
arrowParens:          avoid
printWidth:           80
parser:               typescript
bracketSpacing:       true
useTabs:              false
