name: Release

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Publish new version to NPM
        with:
          node-version: [18.x]
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: yarn
      - run: yarn build
      - run: node pre-publish.js
      - run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}